name: Quality Assurance
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: ./run lint-scripts
    - run: ./run lint-package
    - run: ./run eslint
  test-ts-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1 
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: ./run test-ts-node